// Mock data for Challenge Reward app

const DATA = {
  user: {
    nickname: '지수',
    streak: 7,
    totalProofs: 23,
    points: 1284,
    joinedAt: '2026.03.14',
  },
  myChallenges: [
    {
      id: 'c1',
      title: '하루 물 2L 마시기',
      category: '생활습관',
      seed: 'water',
      daysLeft: 12,
      total: 30,
      streak: 7,
      participants: 248,
      todayDone: false,
      coverColor: '#00AEFF',
    },
    {
      id: 'c2',
      title: '아침 6시 기상 챌린지',
      category: '갓생',
      seed: 'morning',
      daysLeft: 3,
      total: 21,
      streak: 18,
      participants: 86,
      todayDone: true,
      coverColor: '#FF9200',
      endingSoon: true,
    },
    {
      id: 'c3',
      title: '퇴근 후 30분 독서',
      category: '자기계발',
      seed: 'book',
      daysLeft: 24,
      total: 30,
      streak: 5,
      participants: 412,
      todayDone: false,
      coverColor: '#6541F2',
    },
  ],
  popular: [
    { id: 'p1', title: '100일 코딩 챌린지', creator: '민준', participants: 1284, seed: 'code', category: '자기계발', period: '100일' },
    { id: 'p2', title: '주 3회 홈트레이닝', creator: '하늘 PT', participants: 832, seed: 'fit', category: '운동', period: '4주' },
    { id: 'p3', title: '하루 한 끼 식단 사진', creator: '영양사 수민', participants: 567, seed: 'meal', category: '건강', period: '21일' },
    { id: 'p4', title: '매일 영어 단어 10개', creator: '잉글리시', participants: 921, seed: 'eng', category: '공부', period: '30일' },
    { id: 'p5', title: '주말 등산 인증', creator: '산악회', participants: 142, seed: 'hike', category: '운동', period: '12주' },
  ],
  categories: ['전체', '운동', '공부', '생활습관', '자기계발', '갓생', '건강'],
  pending: [
    { id: 'pr1', author: '하늘', challenge: '하루 물 2L 마시기', seed: 'p-water-1', comment: '오늘도 1L 다 마셨어요. 화이팅!', ago: '12분 전', approves: 2, rejects: 0 },
    { id: 'pr2', author: '도윤', challenge: '아침 6시 기상 챌린지', seed: 'p-morn-1', comment: '오늘 일출 진짜 예뻤어요 🌅', ago: '34분 전', approves: 1, rejects: 0 },
    { id: 'pr3', author: '서연', challenge: '퇴근 후 30분 독서', seed: 'p-book-1', comment: '《미움받을 용기》 절반 읽었습니다', ago: '1시간 전', approves: 0, rejects: 0 },
    { id: 'pr4', author: '예준', challenge: '하루 물 2L 마시기', seed: 'p-water-2', comment: '', ago: '2시간 전', approves: 1, rejects: 1 },
    { id: 'pr5', author: '지안', challenge: '퇴근 후 30분 독서', seed: 'p-book-2', comment: '오늘은 한강 작가님', ago: '3시간 전', approves: 2, rejects: 0 },
  ],
  tickets: [
    { id: 't1', from: '하루 물 2L 마시기', earnedAt: '오늘' },
    { id: 't2', from: '아침 6시 기상 챌린지', earnedAt: '오늘' },
    { id: 't3', from: '퇴근 후 30분 독서', earnedAt: '어제' },
    { id: 't4', from: '아침 6시 기상 챌린지', earnedAt: '어제' },
    { id: 't5', from: '하루 물 2L 마시기', earnedAt: '2일 전' },
  ],
  walletTx: [
    { id: 'w1', label: '복권 당첨', amount: 10, when: '오늘 14:32', from: '하루 물 2L 마시기' },
    { id: 'w2', label: '복권 당첨', amount: 1, when: '오늘 08:11', from: '아침 6시 기상' },
    { id: 'w3', label: '복권 당첨', amount: 3, when: '어제 22:04', from: '퇴근 후 30분 독서' },
    { id: 'w4', label: '복권 당첨', amount: 1, when: '어제 13:18', from: '하루 물 2L' },
    { id: 'w5', label: '복권 당첨', amount: 100, when: '2일 전 19:22', from: '아침 6시 기상' },
    { id: 'w6', label: '복권 당첨', amount: 3, when: '2일 전 08:30', from: '하루 물 2L' },
    { id: 'w7', label: '복권 당첨', amount: 5, when: '3일 전 21:00', from: '퇴근 후 30분 독서' },
  ],
  challengeDetail: {
    id: 'c1',
    title: '하루 물 2L 마시기',
    category: '생활습관',
    seed: 'water',
    description: '하루 물 2L를 꾸준히 마시는 습관을 만드는 챌린지입니다. 매일 마신 물병이나 컵 사진을 올려주세요. 카페인 음료나 주스는 인정되지 않아요.',
    creator: '지수',
    creatorJoined: true,
    participants: 248,
    period: '30일',
    daysLeft: 12,
    proofFreq: '하루 1회',
    startDate: '2026.05.10',
    endDate: '2026.06.08',
    recentProofs: ['p1', 'p2', 'p3', 'p4', 'p5', 'p6'],
  },
};

window.DATA = DATA;
